---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife
  namespace: gameoflife-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      labels:
        env1: dev
        app: gameoflife
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: gameoflife
        image: snaidu/gameoflife:1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
