---
apiVersion: v1
kind: Service
metadata:
  name: gameoflife-svc
  namespace: gameoflife-dev
spec:
  selector:
    env1: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
  type: LoadBalancer